In [1]:
import numpy as np
np.set_printoptions(edgeitems=3, infstr='inf', linewidth=75, nanstr='nan',
                   precision=8, suppress=False, threshold=3, formatter=None)

import pyrrhenius.database as phsd

database_location = 'database/publication_database.csv'
ecdatabase = phsd.Database(database_location)

In [2]:
nv17HD  = ecdatabase.get_model('nv_17_ol[010]') # Novella et al. 2017's HD diffusion equation
print(nv17HD)

seo3dry =  ecdatabase.get_model('SEO3_ol') # Constable et al. 2006's dry olivine equation
print(seo3dry)

combined = nv17HD+seo3dry
print(combined)

nv_17_ol[010]:{NerstEinstein2 1.8e+42(nan) 10^-5.0(0.9) 1.782654381(0.196921123) }
SEO3_ol:{e*(5.06e+24(nan) exp( -0.357(nan)/kT) 3.33e+24(nan) exp( -0.02(nan)/kT) fO2^0.166667(nan))*1.22e-05(nan) exp( -1.05(nan)/kT) + e*(4.58e+26(nan) exp( -0.752(nan)/kT) 6.209999999999999e+30(nan) exp( -1.83(nan)/kT) fO2^0.166666667(nan))*5.44e-06(nan) exp( -1.09(nan)/kT)}
nv_17_ol[010]+SEO3_ol:{nv_17_ol[010]:{NerstEinstein2 1.8e+42(nan) 10^-5.0(0.9) 1.782654381(0.196921123) }+SEO3_ol:{e*(5.06e+24(nan) exp( -0.357(nan)/kT) 3.33e+24(nan) exp( -0.02(nan)/kT) fO2^0.166667(nan))*1.22e-05(nan) exp( -1.05(nan)/kT) + e*(4.58e+26(nan) exp( -0.752(nan)/kT) 6.209999999999999e+30(nan) exp( -1.83(nan)/kT) fO2^0.166666667(nan))*5.44e-06(nan) exp( -1.09(nan)/kT)}}


In [3]:
model = ecdatabase.get_model('SEO3_ol')
model.get_conductivity(T=1000, P=1.0, logfo2=10**-11)

array([2.73808615e-05])

In [4]:
T = np.ones(4)*700 # in degrees K
print(T.shape)
model.get_conductivity(T=T, P=1.0, logfo2=10**-11)

(4,)


array([1.29536636e-07, 1.29536636e-07, 1.29536636e-07, 1.29536636e-07])

In [5]:
T = np.ones((4,4))*700 # in degrees K
print(T.shape)
model.get_conductivity(T=T, P=1.0, logfo2=10**-11)

(4, 4)


array([[1.29536636e-07, 1.29536636e-07, 1.29536636e-07, 1.29536636e-07],
       [1.29536636e-07, 1.29536636e-07, 1.29536636e-07, 1.29536636e-07],
       [1.29536636e-07, 1.29536636e-07, 1.29536636e-07, 1.29536636e-07],
       [1.29536636e-07, 1.29536636e-07, 1.29536636e-07, 1.29536636e-07]])

In [6]:
try:
    model.get_conductivity(T=T)
except AssertionError as e:
    print(e)

Did not provide an oxygen fugacity value!


In [7]:
model.print_required_parameters()

Required Keywords
********************
--------------------
Intrinsic Arguments
--------------------
--------------------
Volatile Arguments
--------------------
--------------------
Electronic Conduction Arguments
--------------------
logfo2
--------------------
Diffusion Conduction Arguments
--------------------
--------------------
Polymerizing Agent Arguments
--------------------
